language: java
jdk:
- openjdk11
env:
  global:
  - secure: cUsEowyqrDN2pdKP0zvA87EyHDEy9SRiyeZW3U+8SODOy8e/G+0cz0CpMFQhzFLqVhxI8j6WLxerEyMutPhe2z7ztT0waJziOXOaIlzLAmMVUQ+9BVTomuU0i0mN0956+0b2lwTOdilbikhTlpjLdDYcrgDlaxYaTDceETQuRys=
  - secure: F4gSf65CtXpX4CrFTnn21ewnESfOWQiAzqHVkJ3rP2bDFuhSjE5202mGxSAtUTvaVXgph39LJivKe/RSkYz86aqXBeUXkuRbtxck8eN0eo7QJ2YeqEQsMevOgIFRq80oUURmF9aOaRBY8RjDgsxlO4rVmGBotRMof7VNJnQ6xBU=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
